<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fin</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Finch</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arg-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>end</key>
					<string>\|</string>
					<key>name</key>
					<string>meta.parameter-list.finch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]+</string>
							<key>name</key>
							<string>variable.parameter.finch</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.block.begin.finch</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.block.end.finch</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.block.finch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#arg-list</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block-comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.finch</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.finch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(return|break)\b</string>
					<key>name</key>
					<string>keyword.control.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;--|&lt;-|::)</string>
					<key>name</key>
					<string>keyword.language.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\(\)\[\]\{\}\;\,\.]</string>
					<key>name</key>
					<string>punctuation.separator.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|nil)\b</string>
					<key>name</key>
					<string>constant.language.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(self|undefined)\b</string>
					<key>name</key>
					<string>variable.language.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*]+</string>
					<key>name</key>
					<string>keyword.operator.user.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]*\:</string>
					<key>name</key>
					<string>keyword.user.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*]*[A-Z]+[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]*</string>
					<key>name</key>
					<string>variable.global.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*]*_+[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]*</string>
					<key>name</key>
					<string>variable.object.finch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*]*[a-z]+[A-Za-z0-9\-\+\=\/\&lt;\&gt;\?\~\!\@\#\$\%\^\&amp;\*_]*</string>
					<key>name</key>
					<string>variable.local.finch</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.finch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.finch</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*((//).*$\n?)</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>-?\b[0-9]+(\.[0-9]+)?\b</string>
					<key>name</key>
					<string>constant.numeric.finch</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.finch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.finch</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.finch</string>
	<key>uuid</key>
	<string>DBEA8EDC-A1CA-4CB4-8614-4CFEBEB7E1ED</string>
</dict>
</plist>
